import { Backlink } from "@/types";

export const mockBacklinks: Backlink[] = [
  {
    id: "1",
    sourceUrl: "https://techblog.com/best-seo-tools",
    targetUrl: "https://mysite.com/features",
    anchorText: "best SEO tool",
    status: "active",
    dofollow: true,
    domainAuthority: 72,
    lastChecked: "2024-01-15T10:30:00Z",
    firstSeen: "2023-06-12T08:00:00Z",
  },
  {
    id: "2",
    sourceUrl: "https://marketingweekly.com/link-building-guide",
    targetUrl: "https://mysite.com",
    anchorText: "Link Tracker",
    status: "active",
    dofollow: true,
    domainAuthority: 65,
    lastChecked: "2024-01-15T09:15:00Z",
    firstSeen: "2023-08-22T14:30:00Z",
  },
  {
    id: "3",
    sourceUrl: "https://seoforums.net/threads/useful-tools",
    targetUrl: "https://mysite.com/pricing",
    anchorText: "check it out",
    status: "lost",
    dofollow: false,
    domainAuthority: 45,
    lastChecked: "2024-01-14T16:45:00Z",
    firstSeen: "2023-04-05T11:00:00Z",
  },
  {
    id: "4",
    sourceUrl: "https://digitalnews.io/seo-roundup-january",
    targetUrl: "https://mysite.com/blog",
    anchorText: "mysite blog",
    status: "active",
    dofollow: true,
    domainAuthority: 58,
    lastChecked: "2024-01-15T08:00:00Z",
    firstSeen: "2024-01-02T09:00:00Z",
  },
  {
    id: "5",
    sourceUrl: "https://webmaster-resources.com/backlink-checkers",
    targetUrl: "https://mysite.com",
    anchorText: "backlink checker tool",
    status: "pending",
    dofollow: true,
    domainAuthority: 51,
    lastChecked: "2024-01-13T12:00:00Z",
    firstSeen: "2024-01-10T15:30:00Z",
  },
  {
    id: "6",
    sourceUrl: "https://startuplist.io/seo-tools",
    targetUrl: "https://mysite.com/features",
    anchorText: "Link Tracker features",
    status: "active",
    dofollow: false,
    domainAuthority: 38,
    lastChecked: "2024-01-15T07:30:00Z",
    firstSeen: "2023-11-18T10:00:00Z",
  },
  {
    id: "7",
    sourceUrl: "https://affiliateblog.com/best-affiliate-tools",
    targetUrl: "https://mysite.com/affiliate",
    anchorText: "affiliate program",
    status: "lost",
    dofollow: true,
    domainAuthority: 42,
    lastChecked: "2024-01-12T14:20:00Z",
    firstSeen: "2023-07-30T08:45:00Z",
  },
  {
    id: "8",
    sourceUrl: "https://ecommerce-insights.com/seo-guide",
    targetUrl: "https://mysite.com/blog/ecommerce-seo",
    anchorText: "ecommerce SEO guide",
    status: "active",
    dofollow: true,
    domainAuthority: 61,
    lastChecked: "2024-01-15T11:00:00Z",
    firstSeen: "2023-09-14T16:00:00Z",
  },
  {
    id: "9",
    sourceUrl: "https://freelancer-hub.net/tools-review",
    targetUrl: "https://mysite.com",
    anchorText: "recommended tool",
    status: "active",
    dofollow: true,
    domainAuthority: 33,
    lastChecked: "2024-01-15T06:45:00Z",
    firstSeen: "2023-12-01T12:00:00Z",
  },
  {
    id: "10",
    sourceUrl: "https://agency-directory.com/seo-agencies",
    targetUrl: "https://mysite.com/enterprise",
    anchorText: "enterprise SEO solution",
    status: "pending",
    dofollow: true,
    domainAuthority: 55,
    lastChecked: "2024-01-14T09:30:00Z",
    firstSeen: "2024-01-08T14:00:00Z",
  },
  {
    id: "11",
    sourceUrl: "https://contentmarketer.io/link-building",
    targetUrl: "https://mysite.com/blog",
    anchorText: "content marketing tips",
    status: "active",
    dofollow: true,
    domainAuthority: 48,
    lastChecked: "2024-01-15T10:00:00Z",
    firstSeen: "2023-10-25T11:30:00Z",
  },
  {
    id: "12",
    sourceUrl: "https://smallbiz-resources.com/marketing-tools",
    targetUrl: "https://mysite.com/pricing",
    anchorText: "affordable SEO",
    status: "active",
    dofollow: false,
    domainAuthority: 29,
    lastChecked: "2024-01-15T05:15:00Z",
    firstSeen: "2023-05-17T09:00:00Z",
  },
];
