openapi: 3.0.3
info:
  title: Health Service API
  description: API для мониторинга здоровья сайтов
  version: 1.0.0

servers:
  - url: http://localhost:8084
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /ready:
    get:
      summary: Readiness check
      tags:
        - Health
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadyResponse'
        '503':
          description: Service is not ready

  /api/v1/sites:
    get:
      summary: Get monitored sites list
      tags:
        - Sites
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: is_alive
          in: query
          schema:
            type: boolean
        - name: has_noindex
          in: query
          schema:
            type: boolean
        - name: domain
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Sites list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Add site for monitoring
      tags:
        - Sites
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSiteRequest'
      responses:
        '201':
          description: Site created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonitoredSite'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/sites/{id}:
    get:
      summary: Get site by ID
      tags:
        - Sites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Site details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonitoredSite'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update site
      tags:
        - Sites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSiteRequest'
      responses:
        '200':
          description: Site updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonitoredSite'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete site
      tags:
        - Sites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Site deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/sites/{id}/check:
    post:
      summary: Run health check for site
      tags:
        - Sites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Health check result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteHealthCheck'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/sites/{id}/history:
    get:
      summary: Get site check history
      tags:
        - Sites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: Check history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        service:
          type: string
          example: health-service

    ReadyResponse:
      type: object
      properties:
        status:
          type: string
          example: ready
        service:
          type: string
          example: health-service

    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    MonitoredSite:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        url:
          type: string
        domain:
          type: string
        http_status:
          type: integer
          nullable: true
        is_alive:
          type: boolean
        response_time_ms:
          type: integer
          nullable: true
        allows_indexing:
          type: boolean
          nullable: true
        robots_txt_status:
          type: string
        has_noindex:
          type: boolean
        pages_indexed:
          type: integer
        last_checked_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time

    SiteCheckHistory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        site_id:
          type: integer
          format: int64
        http_status:
          type: integer
          nullable: true
        is_alive:
          type: boolean
        response_time_ms:
          type: integer
          nullable: true
        checked_at:
          type: string
          format: date-time

    SiteHealthCheck:
      type: object
      properties:
        site_id:
          type: integer
          format: int64
        url:
          type: string
        http_status:
          type: integer
        is_alive:
          type: boolean
        response_time_ms:
          type: integer
        allows_indexing:
          type: boolean
        robots_txt_status:
          type: string
        has_noindex:
          type: boolean
        checked_at:
          type: string
          format: date-time
        error:
          type: string

    CreateSiteRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string

    UpdateSiteRequest:
      type: object
      properties:
        url:
          type: string
        pages_indexed:
          type: integer

    SiteListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/MonitoredSite'
        page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer
          format: int64
        total_pages:
          type: integer
          format: int64

    HistoryListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/SiteCheckHistory'
        page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer
          format: int64
        total_pages:
          type: integer
          format: int64
