openapi: 3.0.3
info:
  title: Index Service API
  description: API для проверки индексации URL в поисковых системах
  version: 1.0.0

servers:
  - url: http://localhost:8083
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /ready:
    get:
      summary: Readiness check
      tags:
        - Health
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadyResponse'
        '503':
          description: Service is not ready

  /api/v1/platforms:
    get:
      summary: Get platforms list
      tags:
        - Platforms
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: index_status
          in: query
          schema:
            type: string
            enum: [pending, indexed, not_indexed, error]
        - name: is_indexed
          in: query
          schema:
            type: boolean
        - name: is_must_have
          in: query
          schema:
            type: boolean
        - name: domain
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Platforms list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create platform
      tags:
        - Platforms
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePlatformRequest'
      responses:
        '201':
          description: Platform created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/platforms/bulk:
    post:
      summary: Bulk create platforms
      tags:
        - Platforms
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkCreatePlatformsRequest'
      responses:
        '200':
          description: Bulk operation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkOperationResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/platforms/{id}:
    get:
      summary: Get platform by ID
      tags:
        - Platforms
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Platform details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update platform
      tags:
        - Platforms
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlatformRequest'
      responses:
        '200':
          description: Platform updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Platform'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete platform
      tags:
        - Platforms
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Platform deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/v1/platforms/{id}/check:
    post:
      summary: Check platform indexation
      tags:
        - Platforms
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Index check result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexCheckResult'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        service:
          type: string
          example: index-service

    ReadyResponse:
      type: object
      properties:
        status:
          type: string
          example: ready
        service:
          type: string
          example: index-service

    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    Platform:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        url:
          type: string
        domain:
          type: string
        index_status:
          type: string
          enum: [pending, indexed, not_indexed, error]
        is_indexed:
          type: boolean
        first_indexed_at:
          type: string
          format: date-time
          nullable: true
        last_checked_at:
          type: string
          format: date-time
          nullable: true
        check_count:
          type: integer
        potential_score:
          type: integer
        is_must_have:
          type: boolean
        notes:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreatePlatformRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
        potential_score:
          type: integer
        is_must_have:
          type: boolean
        notes:
          type: string

    UpdatePlatformRequest:
      type: object
      properties:
        url:
          type: string
        potential_score:
          type: integer
        is_must_have:
          type: boolean
        notes:
          type: string

    BulkCreatePlatformsRequest:
      type: object
      required:
        - platforms
      properties:
        platforms:
          type: array
          items:
            $ref: '#/components/schemas/CreatePlatformRequest'
          maxItems: 100

    BulkOperationResponse:
      type: object
      properties:
        success:
          type: integer
        failed:
          type: integer
        errors:
          type: array
          items:
            type: object
            properties:
              index:
                type: integer
              url:
                type: string
              message:
                type: string
        created:
          type: array
          items:
            $ref: '#/components/schemas/Platform'

    IndexCheckResult:
      type: object
      properties:
        platform_id:
          type: integer
          format: int64
        url:
          type: string
        http_status:
          type: integer
        is_indexed:
          type: boolean
        index_status:
          type: string
          enum: [pending, indexed, not_indexed, error]
        checked_at:
          type: string
          format: date-time
        error:
          type: string

    PlatformListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Platform'
        page:
          type: integer
        per_page:
          type: integer
        total:
          type: integer
          format: int64
        total_pages:
          type: integer
          format: int64
